# Generated by Django 4.2.6 on 2024-04-07 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MethodBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('institute', models.CharField(max_length=255)),
                ('type_of_work', models.CharField(max_length=255)),
                ('name_of_work', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('date_publish', models.DateField()),
                ('agreement_author_id', models.IntegerField(null=True)),
                ('agreement_date', models.DateField(null=True)),
                ('authors', models.ManyToManyField(related_name='method_books', to='myapp.author')),
            ],
        ),
    ]
